package com.adups.kafka.bean.gemini;

import java.math.BigDecimal;
import java.util.Date;

public class TOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_sn
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.group_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_type
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.business_model_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String businessModelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_address_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String orderAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.store_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.eshop_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String eshopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_source
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String orderSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.invoice_status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String invoiceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.buyer_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String buyerRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.seller_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String sellerRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.employee_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String employeeRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.store_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String storeRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.abnormal_type
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String abnormalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.abnormal_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String abnormalRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.delivery_type
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String deliveryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.trading_price
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private BigDecimal tradingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.payable_price
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private BigDecimal payablePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.score
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.is_split
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String isSplit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.employee_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.employee_phone
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String employeePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.employee_name
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String employeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.appointment_start_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Date appointmentStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.appointment_end_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Date appointmentEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.eshop_combo_pro_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String eshopComboProId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.expiry_date
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Date expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.combo_price
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private BigDecimal comboPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total_quantity
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Integer totalQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.groupon_instance_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String grouponInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.version
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_user
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.update_user
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.update_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.create_user_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.update_user_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_sn_reserve
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String orderSnReserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.normal_store_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String normalStoreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.third_part
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String thirdPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.sign_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Date signTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_sn
     *
     * @return the value of t_order.order_sn
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_sn
     *
     * @param orderSn the value for t_order.order_sn
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.group_id
     *
     * @return the value of t_order.group_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.group_id
     *
     * @param groupId the value for t_order.group_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_type
     *
     * @return the value of t_order.order_type
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_type
     *
     * @param orderType the value for t_order.order_type
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.business_model_id
     *
     * @return the value of t_order.business_model_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getBusinessModelId() {
        return businessModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.business_model_id
     *
     * @param businessModelId the value for t_order.business_model_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setBusinessModelId(String businessModelId) {
        this.businessModelId = businessModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_id
     *
     * @return the value of t_order.customer_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customer_id
     *
     * @param customerId the value for t_order.customer_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_address_id
     *
     * @return the value of t_order.order_address_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getOrderAddressId() {
        return orderAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_address_id
     *
     * @param orderAddressId the value for t_order.order_address_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setOrderAddressId(String orderAddressId) {
        this.orderAddressId = orderAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.store_id
     *
     * @return the value of t_order.store_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.store_id
     *
     * @param storeId the value for t_order.store_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.eshop_id
     *
     * @return the value of t_order.eshop_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getEshopId() {
        return eshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.eshop_id
     *
     * @param eshopId the value for t_order.eshop_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setEshopId(String eshopId) {
        this.eshopId = eshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_status
     *
     * @return the value of t_order.order_status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_status
     *
     * @param orderStatus the value for t_order.order_status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_source
     *
     * @return the value of t_order.order_source
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getOrderSource() {
        return orderSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_source
     *
     * @param orderSource the value for t_order.order_source
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setOrderSource(String orderSource) {
        this.orderSource = orderSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.invoice_status
     *
     * @return the value of t_order.invoice_status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getInvoiceStatus() {
        return invoiceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.invoice_status
     *
     * @param invoiceStatus the value for t_order.invoice_status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setInvoiceStatus(String invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.buyer_remark
     *
     * @return the value of t_order.buyer_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getBuyerRemark() {
        return buyerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.buyer_remark
     *
     * @param buyerRemark the value for t_order.buyer_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setBuyerRemark(String buyerRemark) {
        this.buyerRemark = buyerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.seller_remark
     *
     * @return the value of t_order.seller_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getSellerRemark() {
        return sellerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.seller_remark
     *
     * @param sellerRemark the value for t_order.seller_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setSellerRemark(String sellerRemark) {
        this.sellerRemark = sellerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.employee_remark
     *
     * @return the value of t_order.employee_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getEmployeeRemark() {
        return employeeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.employee_remark
     *
     * @param employeeRemark the value for t_order.employee_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setEmployeeRemark(String employeeRemark) {
        this.employeeRemark = employeeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.store_remark
     *
     * @return the value of t_order.store_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getStoreRemark() {
        return storeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.store_remark
     *
     * @param storeRemark the value for t_order.store_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setStoreRemark(String storeRemark) {
        this.storeRemark = storeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.abnormal_type
     *
     * @return the value of t_order.abnormal_type
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getAbnormalType() {
        return abnormalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.abnormal_type
     *
     * @param abnormalType the value for t_order.abnormal_type
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setAbnormalType(String abnormalType) {
        this.abnormalType = abnormalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.abnormal_remark
     *
     * @return the value of t_order.abnormal_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getAbnormalRemark() {
        return abnormalRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.abnormal_remark
     *
     * @param abnormalRemark the value for t_order.abnormal_remark
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setAbnormalRemark(String abnormalRemark) {
        this.abnormalRemark = abnormalRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.delivery_type
     *
     * @return the value of t_order.delivery_type
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.delivery_type
     *
     * @param deliveryType the value for t_order.delivery_type
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setDeliveryType(String deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.trading_price
     *
     * @return the value of t_order.trading_price
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public BigDecimal getTradingPrice() {
        return tradingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.trading_price
     *
     * @param tradingPrice the value for t_order.trading_price
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setTradingPrice(BigDecimal tradingPrice) {
        this.tradingPrice = tradingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.payable_price
     *
     * @return the value of t_order.payable_price
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public BigDecimal getPayablePrice() {
        return payablePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.payable_price
     *
     * @param payablePrice the value for t_order.payable_price
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setPayablePrice(BigDecimal payablePrice) {
        this.payablePrice = payablePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.score
     *
     * @return the value of t_order.score
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.score
     *
     * @param score the value for t_order.score
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.is_split
     *
     * @return the value of t_order.is_split
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getIsSplit() {
        return isSplit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.is_split
     *
     * @param isSplit the value for t_order.is_split
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setIsSplit(String isSplit) {
        this.isSplit = isSplit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.employee_id
     *
     * @return the value of t_order.employee_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.employee_id
     *
     * @param employeeId the value for t_order.employee_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.employee_phone
     *
     * @return the value of t_order.employee_phone
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getEmployeePhone() {
        return employeePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.employee_phone
     *
     * @param employeePhone the value for t_order.employee_phone
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setEmployeePhone(String employeePhone) {
        this.employeePhone = employeePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.employee_name
     *
     * @return the value of t_order.employee_name
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.employee_name
     *
     * @param employeeName the value for t_order.employee_name
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.appointment_start_time
     *
     * @return the value of t_order.appointment_start_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Date getAppointmentStartTime() {
        return appointmentStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.appointment_start_time
     *
     * @param appointmentStartTime the value for t_order.appointment_start_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setAppointmentStartTime(Date appointmentStartTime) {
        this.appointmentStartTime = appointmentStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.appointment_end_time
     *
     * @return the value of t_order.appointment_end_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Date getAppointmentEndTime() {
        return appointmentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.appointment_end_time
     *
     * @param appointmentEndTime the value for t_order.appointment_end_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setAppointmentEndTime(Date appointmentEndTime) {
        this.appointmentEndTime = appointmentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.eshop_combo_pro_id
     *
     * @return the value of t_order.eshop_combo_pro_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getEshopComboProId() {
        return eshopComboProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.eshop_combo_pro_id
     *
     * @param eshopComboProId the value for t_order.eshop_combo_pro_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setEshopComboProId(String eshopComboProId) {
        this.eshopComboProId = eshopComboProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.expiry_date
     *
     * @return the value of t_order.expiry_date
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.expiry_date
     *
     * @param expiryDate the value for t_order.expiry_date
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.combo_price
     *
     * @return the value of t_order.combo_price
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public BigDecimal getComboPrice() {
        return comboPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.combo_price
     *
     * @param comboPrice the value for t_order.combo_price
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setComboPrice(BigDecimal comboPrice) {
        this.comboPrice = comboPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.total_quantity
     *
     * @return the value of t_order.total_quantity
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Integer getTotalQuantity() {
        return totalQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.total_quantity
     *
     * @param totalQuantity the value for t_order.total_quantity
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setTotalQuantity(Integer totalQuantity) {
        this.totalQuantity = totalQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.groupon_instance_id
     *
     * @return the value of t_order.groupon_instance_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getGrouponInstanceId() {
        return grouponInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.groupon_instance_id
     *
     * @param grouponInstanceId the value for t_order.groupon_instance_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setGrouponInstanceId(String grouponInstanceId) {
        this.grouponInstanceId = grouponInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.version
     *
     * @return the value of t_order.version
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.version
     *
     * @param version the value for t_order.version
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_user
     *
     * @return the value of t_order.create_user
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_user
     *
     * @param createUser the value for t_order.create_user
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_time
     *
     * @return the value of t_order.create_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_time
     *
     * @param createTime the value for t_order.create_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.update_user
     *
     * @return the value of t_order.update_user
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.update_user
     *
     * @param updateUser the value for t_order.update_user
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.update_time
     *
     * @return the value of t_order.update_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.update_time
     *
     * @param updateTime the value for t_order.update_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.create_user_id
     *
     * @return the value of t_order.create_user_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.create_user_id
     *
     * @param createUserId the value for t_order.create_user_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.update_user_id
     *
     * @return the value of t_order.update_user_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.update_user_id
     *
     * @param updateUserId the value for t_order.update_user_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_sn_reserve
     *
     * @return the value of t_order.order_sn_reserve
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getOrderSnReserve() {
        return orderSnReserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_sn_reserve
     *
     * @param orderSnReserve the value for t_order.order_sn_reserve
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setOrderSnReserve(String orderSnReserve) {
        this.orderSnReserve = orderSnReserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.normal_store_id
     *
     * @return the value of t_order.normal_store_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getNormalStoreId() {
        return normalStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.normal_store_id
     *
     * @param normalStoreId the value for t_order.normal_store_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setNormalStoreId(String normalStoreId) {
        this.normalStoreId = normalStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.third_part
     *
     * @return the value of t_order.third_part
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getThirdPart() {
        return thirdPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.third_part
     *
     * @param thirdPart the value for t_order.third_part
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setThirdPart(String thirdPart) {
        this.thirdPart = thirdPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.sign_time
     *
     * @return the value of t_order.sign_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.sign_time
     *
     * @param signTime the value for t_order.sign_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }
}