package com.adups.kafka.bean.gemini;

import java.util.Date;

public class TOrderFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.order_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.user_type
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.employee_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.employee_phone
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String employeePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.employee_name
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String employeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.appointment_start_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Date appointmentStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.appointment_end_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Date appointmentEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.order_status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.version
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.create_user_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.create_user
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.create_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.update_user_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.update_user
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_flow.update_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.id
     *
     * @return the value of t_order_flow.id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.id
     *
     * @param id the value for t_order_flow.id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.order_id
     *
     * @return the value of t_order_flow.order_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.order_id
     *
     * @param orderId the value for t_order_flow.order_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.user_type
     *
     * @return the value of t_order_flow.user_type
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.user_type
     *
     * @param userType the value for t_order_flow.user_type
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.employee_id
     *
     * @return the value of t_order_flow.employee_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.employee_id
     *
     * @param employeeId the value for t_order_flow.employee_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.employee_phone
     *
     * @return the value of t_order_flow.employee_phone
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getEmployeePhone() {
        return employeePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.employee_phone
     *
     * @param employeePhone the value for t_order_flow.employee_phone
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setEmployeePhone(String employeePhone) {
        this.employeePhone = employeePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.employee_name
     *
     * @return the value of t_order_flow.employee_name
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.employee_name
     *
     * @param employeeName the value for t_order_flow.employee_name
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.appointment_start_time
     *
     * @return the value of t_order_flow.appointment_start_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Date getAppointmentStartTime() {
        return appointmentStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.appointment_start_time
     *
     * @param appointmentStartTime the value for t_order_flow.appointment_start_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setAppointmentStartTime(Date appointmentStartTime) {
        this.appointmentStartTime = appointmentStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.appointment_end_time
     *
     * @return the value of t_order_flow.appointment_end_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Date getAppointmentEndTime() {
        return appointmentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.appointment_end_time
     *
     * @param appointmentEndTime the value for t_order_flow.appointment_end_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setAppointmentEndTime(Date appointmentEndTime) {
        this.appointmentEndTime = appointmentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.order_status
     *
     * @return the value of t_order_flow.order_status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.order_status
     *
     * @param orderStatus the value for t_order_flow.order_status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.status
     *
     * @return the value of t_order_flow.status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.status
     *
     * @param status the value for t_order_flow.status
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.version
     *
     * @return the value of t_order_flow.version
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.version
     *
     * @param version the value for t_order_flow.version
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.create_user_id
     *
     * @return the value of t_order_flow.create_user_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.create_user_id
     *
     * @param createUserId the value for t_order_flow.create_user_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.create_user
     *
     * @return the value of t_order_flow.create_user
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.create_user
     *
     * @param createUser the value for t_order_flow.create_user
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.create_time
     *
     * @return the value of t_order_flow.create_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.create_time
     *
     * @param createTime the value for t_order_flow.create_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.update_user_id
     *
     * @return the value of t_order_flow.update_user_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.update_user_id
     *
     * @param updateUserId the value for t_order_flow.update_user_id
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.update_user
     *
     * @return the value of t_order_flow.update_user
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.update_user
     *
     * @param updateUser the value for t_order_flow.update_user
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_flow.update_time
     *
     * @return the value of t_order_flow.update_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_flow.update_time
     *
     * @param updateTime the value for t_order_flow.update_time
     *
     * @mbggenerated Tue Jan 23 18:02:04 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}