package com.adups.kafka.bean.datacube;

import java.math.BigDecimal;
import java.util.Date;

public class BbTOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.customer_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.store_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.store_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.eshop_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String eshopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.eshop_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String eshopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.province_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.city_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.ad_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String adCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.province_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.city_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.branch_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.department_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.role_name_department
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String roleNameDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.role_name_chanel
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String roleNameChanel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.order_source
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String orderSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.order_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.business_model_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String businessModelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.business_model_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String businessModelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.eshop_self
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String eshopSelf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.customer_white
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String customerWhite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.customer_source
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String customerSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.returned_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private BigDecimal returnedPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.place_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private BigDecimal placePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.success_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private BigDecimal successPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.success_payable_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private BigDecimal successPayablePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.cancel_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private BigDecimal cancelPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.place_count
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Integer placeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.success_count
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Integer successCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.cancel_count
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Integer cancelCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.returned_count
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Integer returnedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.min_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date minTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.max_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date maxTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.flow_max_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date flowMaxTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.last_modify_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.month_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String monthTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bb_t_order.company_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.id
     *
     * @return the value of bb_t_order.id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.id
     *
     * @param id the value for bb_t_order.id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.customer_id
     *
     * @return the value of bb_t_order.customer_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.customer_id
     *
     * @param customerId the value for bb_t_order.customer_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.store_id
     *
     * @return the value of bb_t_order.store_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.store_id
     *
     * @param storeId the value for bb_t_order.store_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.store_name
     *
     * @return the value of bb_t_order.store_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.store_name
     *
     * @param storeName the value for bb_t_order.store_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.eshop_id
     *
     * @return the value of bb_t_order.eshop_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEshopId() {
        return eshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.eshop_id
     *
     * @param eshopId the value for bb_t_order.eshop_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopId(String eshopId) {
        this.eshopId = eshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.eshop_name
     *
     * @return the value of bb_t_order.eshop_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEshopName() {
        return eshopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.eshop_name
     *
     * @param eshopName the value for bb_t_order.eshop_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopName(String eshopName) {
        this.eshopName = eshopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.province_code
     *
     * @return the value of bb_t_order.province_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.province_code
     *
     * @param provinceCode the value for bb_t_order.province_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.city_code
     *
     * @return the value of bb_t_order.city_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.city_code
     *
     * @param cityCode the value for bb_t_order.city_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.ad_code
     *
     * @return the value of bb_t_order.ad_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getAdCode() {
        return adCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.ad_code
     *
     * @param adCode the value for bb_t_order.ad_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setAdCode(String adCode) {
        this.adCode = adCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.province_name
     *
     * @return the value of bb_t_order.province_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.province_name
     *
     * @param provinceName the value for bb_t_order.province_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.city_name
     *
     * @return the value of bb_t_order.city_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.city_name
     *
     * @param cityName the value for bb_t_order.city_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.branch_id
     *
     * @return the value of bb_t_order.branch_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.branch_id
     *
     * @param branchId the value for bb_t_order.branch_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.department_id
     *
     * @return the value of bb_t_order.department_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.department_id
     *
     * @param departmentId the value for bb_t_order.department_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.role_name_department
     *
     * @return the value of bb_t_order.role_name_department
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getRoleNameDepartment() {
        return roleNameDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.role_name_department
     *
     * @param roleNameDepartment the value for bb_t_order.role_name_department
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setRoleNameDepartment(String roleNameDepartment) {
        this.roleNameDepartment = roleNameDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.role_name_chanel
     *
     * @return the value of bb_t_order.role_name_chanel
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getRoleNameChanel() {
        return roleNameChanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.role_name_chanel
     *
     * @param roleNameChanel the value for bb_t_order.role_name_chanel
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setRoleNameChanel(String roleNameChanel) {
        this.roleNameChanel = roleNameChanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.order_source
     *
     * @return the value of bb_t_order.order_source
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getOrderSource() {
        return orderSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.order_source
     *
     * @param orderSource the value for bb_t_order.order_source
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderSource(String orderSource) {
        this.orderSource = orderSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.order_type
     *
     * @return the value of bb_t_order.order_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.order_type
     *
     * @param orderType the value for bb_t_order.order_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.business_model_id
     *
     * @return the value of bb_t_order.business_model_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getBusinessModelId() {
        return businessModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.business_model_id
     *
     * @param businessModelId the value for bb_t_order.business_model_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setBusinessModelId(String businessModelId) {
        this.businessModelId = businessModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.business_model_name
     *
     * @return the value of bb_t_order.business_model_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getBusinessModelName() {
        return businessModelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.business_model_name
     *
     * @param businessModelName the value for bb_t_order.business_model_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setBusinessModelName(String businessModelName) {
        this.businessModelName = businessModelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.eshop_self
     *
     * @return the value of bb_t_order.eshop_self
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEshopSelf() {
        return eshopSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.eshop_self
     *
     * @param eshopSelf the value for bb_t_order.eshop_self
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopSelf(String eshopSelf) {
        this.eshopSelf = eshopSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.customer_white
     *
     * @return the value of bb_t_order.customer_white
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCustomerWhite() {
        return customerWhite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.customer_white
     *
     * @param customerWhite the value for bb_t_order.customer_white
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCustomerWhite(String customerWhite) {
        this.customerWhite = customerWhite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.customer_source
     *
     * @return the value of bb_t_order.customer_source
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCustomerSource() {
        return customerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.customer_source
     *
     * @param customerSource the value for bb_t_order.customer_source
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCustomerSource(String customerSource) {
        this.customerSource = customerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.returned_price
     *
     * @return the value of bb_t_order.returned_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public BigDecimal getReturnedPrice() {
        return returnedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.returned_price
     *
     * @param returnedPrice the value for bb_t_order.returned_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setReturnedPrice(BigDecimal returnedPrice) {
        this.returnedPrice = returnedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.place_price
     *
     * @return the value of bb_t_order.place_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public BigDecimal getPlacePrice() {
        return placePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.place_price
     *
     * @param placePrice the value for bb_t_order.place_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setPlacePrice(BigDecimal placePrice) {
        this.placePrice = placePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.success_price
     *
     * @return the value of bb_t_order.success_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public BigDecimal getSuccessPrice() {
        return successPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.success_price
     *
     * @param successPrice the value for bb_t_order.success_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setSuccessPrice(BigDecimal successPrice) {
        this.successPrice = successPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.success_payable_price
     *
     * @return the value of bb_t_order.success_payable_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public BigDecimal getSuccessPayablePrice() {
        return successPayablePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.success_payable_price
     *
     * @param successPayablePrice the value for bb_t_order.success_payable_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setSuccessPayablePrice(BigDecimal successPayablePrice) {
        this.successPayablePrice = successPayablePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.cancel_price
     *
     * @return the value of bb_t_order.cancel_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public BigDecimal getCancelPrice() {
        return cancelPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.cancel_price
     *
     * @param cancelPrice the value for bb_t_order.cancel_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCancelPrice(BigDecimal cancelPrice) {
        this.cancelPrice = cancelPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.place_count
     *
     * @return the value of bb_t_order.place_count
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Integer getPlaceCount() {
        return placeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.place_count
     *
     * @param placeCount the value for bb_t_order.place_count
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setPlaceCount(Integer placeCount) {
        this.placeCount = placeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.success_count
     *
     * @return the value of bb_t_order.success_count
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Integer getSuccessCount() {
        return successCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.success_count
     *
     * @param successCount the value for bb_t_order.success_count
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setSuccessCount(Integer successCount) {
        this.successCount = successCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.cancel_count
     *
     * @return the value of bb_t_order.cancel_count
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Integer getCancelCount() {
        return cancelCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.cancel_count
     *
     * @param cancelCount the value for bb_t_order.cancel_count
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCancelCount(Integer cancelCount) {
        this.cancelCount = cancelCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.returned_count
     *
     * @return the value of bb_t_order.returned_count
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Integer getReturnedCount() {
        return returnedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.returned_count
     *
     * @param returnedCount the value for bb_t_order.returned_count
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setReturnedCount(Integer returnedCount) {
        this.returnedCount = returnedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.min_time
     *
     * @return the value of bb_t_order.min_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getMinTime() {
        return minTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.min_time
     *
     * @param minTime the value for bb_t_order.min_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setMinTime(Date minTime) {
        this.minTime = minTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.max_time
     *
     * @return the value of bb_t_order.max_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getMaxTime() {
        return maxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.max_time
     *
     * @param maxTime the value for bb_t_order.max_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setMaxTime(Date maxTime) {
        this.maxTime = maxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.flow_max_time
     *
     * @return the value of bb_t_order.flow_max_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getFlowMaxTime() {
        return flowMaxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.flow_max_time
     *
     * @param flowMaxTime the value for bb_t_order.flow_max_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setFlowMaxTime(Date flowMaxTime) {
        this.flowMaxTime = flowMaxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.last_modify_time
     *
     * @return the value of bb_t_order.last_modify_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.last_modify_time
     *
     * @param lastModifyTime the value for bb_t_order.last_modify_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.month_time
     *
     * @return the value of bb_t_order.month_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getMonthTime() {
        return monthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.month_time
     *
     * @param monthTime the value for bb_t_order.month_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setMonthTime(String monthTime) {
        this.monthTime = monthTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bb_t_order.company_id
     *
     * @return the value of bb_t_order.company_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bb_t_order.company_id
     *
     * @param companyId the value for bb_t_order.company_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
}