package com.adups.kafka.bean.datacube;

import java.math.BigDecimal;
import java.util.Date;

public class TOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_sn
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.group_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_freight
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Integer orderFreight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_refund_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private BigDecimal orderRefundPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_refund_status
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String orderRefundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_refund_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date orderRefundTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.business_model_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String businessModelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.business_model_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String businessModelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.card_content_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String cardContentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.card_content_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private BigDecimal cardContentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.card_content_buyprice
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private BigDecimal cardContentBuyprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.card_content_batch
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String cardContentBatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.card_content_platform
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String cardContentPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.card_content_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String cardContentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_mobilephone
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String customerMobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String customerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_source
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String customerSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_white
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String customerWhite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_device_os
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String customerDeviceOs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_create_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date customerCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.department_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.role_name_department
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String roleNameDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.role_name_chanel
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String roleNameChanel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_address_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String orderAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_address
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String orderAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_address_mobilephone
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String orderAddressMobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_address_latitude
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Double orderAddressLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_address_longitude
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Double orderAddressLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_signed_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date orderSignedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_commented_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date orderCommentedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_success_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date orderSuccessTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_cancel_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date orderCancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.store_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.store_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.store_province_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String storeProvinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.store_city_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String storeCityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.store_ad_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String storeAdCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.store_white
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String storeWhite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.store_create_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date storeCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.eshop_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String eshopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.eshop_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String eshopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.eshopseller_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String eshopsellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.eshop_self
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String eshopSelf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.eshop_white
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String eshopWhite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.eshop_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String eshopType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.eshop_kind
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String eshopKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.eshop_self_inventory
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String eshopSelfInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.eshop_send_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String eshopSendType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.eshop_create_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date eshopCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_status
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_source
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String orderSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.abnormal_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String abnormalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.abnormal_remark
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String abnormalRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.delivery_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String deliveryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.trading_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private BigDecimal tradingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.payable_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private BigDecimal payablePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.score
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.is_split
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String isSplit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.employee_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.employee_phone
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String employeePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.employee_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String employeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.appointment_start_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date appointmentStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.appointment_end_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date appointmentEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.eshop_combo_pro_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String eshopComboProId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.combo_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private BigDecimal comboPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total_quantity
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Integer totalQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_create_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date orderCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.flag_joyCard
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Integer flagJoycard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.flag_two
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Integer flagTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.flag_three
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Integer flagThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.flag_four
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Integer flagFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.last_modify_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.groupon_state
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String grouponState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.branch_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String customerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.company_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    private String companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_sn
     *
     * @return the value of t_order.order_sn
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_sn
     *
     * @param orderSn the value for t_order.order_sn
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.group_id
     *
     * @return the value of t_order.group_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.group_id
     *
     * @param groupId the value for t_order.group_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_freight
     *
     * @return the value of t_order.order_freight
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Integer getOrderFreight() {
        return orderFreight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_freight
     *
     * @param orderFreight the value for t_order.order_freight
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderFreight(Integer orderFreight) {
        this.orderFreight = orderFreight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_refund_price
     *
     * @return the value of t_order.order_refund_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public BigDecimal getOrderRefundPrice() {
        return orderRefundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_refund_price
     *
     * @param orderRefundPrice the value for t_order.order_refund_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderRefundPrice(BigDecimal orderRefundPrice) {
        this.orderRefundPrice = orderRefundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_refund_status
     *
     * @return the value of t_order.order_refund_status
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getOrderRefundStatus() {
        return orderRefundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_refund_status
     *
     * @param orderRefundStatus the value for t_order.order_refund_status
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderRefundStatus(String orderRefundStatus) {
        this.orderRefundStatus = orderRefundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_refund_time
     *
     * @return the value of t_order.order_refund_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getOrderRefundTime() {
        return orderRefundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_refund_time
     *
     * @param orderRefundTime the value for t_order.order_refund_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderRefundTime(Date orderRefundTime) {
        this.orderRefundTime = orderRefundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_type
     *
     * @return the value of t_order.order_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_type
     *
     * @param orderType the value for t_order.order_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.business_model_id
     *
     * @return the value of t_order.business_model_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getBusinessModelId() {
        return businessModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.business_model_id
     *
     * @param businessModelId the value for t_order.business_model_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setBusinessModelId(String businessModelId) {
        this.businessModelId = businessModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.business_model_name
     *
     * @return the value of t_order.business_model_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getBusinessModelName() {
        return businessModelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.business_model_name
     *
     * @param businessModelName the value for t_order.business_model_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setBusinessModelName(String businessModelName) {
        this.businessModelName = businessModelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.card_content_type
     *
     * @return the value of t_order.card_content_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCardContentType() {
        return cardContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.card_content_type
     *
     * @param cardContentType the value for t_order.card_content_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCardContentType(String cardContentType) {
        this.cardContentType = cardContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.card_content_price
     *
     * @return the value of t_order.card_content_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public BigDecimal getCardContentPrice() {
        return cardContentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.card_content_price
     *
     * @param cardContentPrice the value for t_order.card_content_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCardContentPrice(BigDecimal cardContentPrice) {
        this.cardContentPrice = cardContentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.card_content_buyprice
     *
     * @return the value of t_order.card_content_buyprice
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public BigDecimal getCardContentBuyprice() {
        return cardContentBuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.card_content_buyprice
     *
     * @param cardContentBuyprice the value for t_order.card_content_buyprice
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCardContentBuyprice(BigDecimal cardContentBuyprice) {
        this.cardContentBuyprice = cardContentBuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.card_content_batch
     *
     * @return the value of t_order.card_content_batch
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCardContentBatch() {
        return cardContentBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.card_content_batch
     *
     * @param cardContentBatch the value for t_order.card_content_batch
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCardContentBatch(String cardContentBatch) {
        this.cardContentBatch = cardContentBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.card_content_platform
     *
     * @return the value of t_order.card_content_platform
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCardContentPlatform() {
        return cardContentPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.card_content_platform
     *
     * @param cardContentPlatform the value for t_order.card_content_platform
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCardContentPlatform(String cardContentPlatform) {
        this.cardContentPlatform = cardContentPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.card_content_name
     *
     * @return the value of t_order.card_content_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCardContentName() {
        return cardContentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.card_content_name
     *
     * @param cardContentName the value for t_order.card_content_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCardContentName(String cardContentName) {
        this.cardContentName = cardContentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_id
     *
     * @return the value of t_order.customer_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customer_id
     *
     * @param customerId the value for t_order.customer_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_mobilephone
     *
     * @return the value of t_order.customer_mobilephone
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCustomerMobilephone() {
        return customerMobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customer_mobilephone
     *
     * @param customerMobilephone the value for t_order.customer_mobilephone
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCustomerMobilephone(String customerMobilephone) {
        this.customerMobilephone = customerMobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_type
     *
     * @return the value of t_order.customer_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customer_type
     *
     * @param customerType the value for t_order.customer_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_source
     *
     * @return the value of t_order.customer_source
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCustomerSource() {
        return customerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customer_source
     *
     * @param customerSource the value for t_order.customer_source
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCustomerSource(String customerSource) {
        this.customerSource = customerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_white
     *
     * @return the value of t_order.customer_white
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCustomerWhite() {
        return customerWhite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customer_white
     *
     * @param customerWhite the value for t_order.customer_white
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCustomerWhite(String customerWhite) {
        this.customerWhite = customerWhite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_device_os
     *
     * @return the value of t_order.customer_device_os
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCustomerDeviceOs() {
        return customerDeviceOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customer_device_os
     *
     * @param customerDeviceOs the value for t_order.customer_device_os
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCustomerDeviceOs(String customerDeviceOs) {
        this.customerDeviceOs = customerDeviceOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_create_time
     *
     * @return the value of t_order.customer_create_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getCustomerCreateTime() {
        return customerCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customer_create_time
     *
     * @param customerCreateTime the value for t_order.customer_create_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCustomerCreateTime(Date customerCreateTime) {
        this.customerCreateTime = customerCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.department_id
     *
     * @return the value of t_order.department_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.department_id
     *
     * @param departmentId the value for t_order.department_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.role_name_department
     *
     * @return the value of t_order.role_name_department
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getRoleNameDepartment() {
        return roleNameDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.role_name_department
     *
     * @param roleNameDepartment the value for t_order.role_name_department
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setRoleNameDepartment(String roleNameDepartment) {
        this.roleNameDepartment = roleNameDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.role_name_chanel
     *
     * @return the value of t_order.role_name_chanel
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getRoleNameChanel() {
        return roleNameChanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.role_name_chanel
     *
     * @param roleNameChanel the value for t_order.role_name_chanel
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setRoleNameChanel(String roleNameChanel) {
        this.roleNameChanel = roleNameChanel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_address_id
     *
     * @return the value of t_order.order_address_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getOrderAddressId() {
        return orderAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_address_id
     *
     * @param orderAddressId the value for t_order.order_address_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderAddressId(String orderAddressId) {
        this.orderAddressId = orderAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_address
     *
     * @return the value of t_order.order_address
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getOrderAddress() {
        return orderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_address
     *
     * @param orderAddress the value for t_order.order_address
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderAddress(String orderAddress) {
        this.orderAddress = orderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_address_mobilephone
     *
     * @return the value of t_order.order_address_mobilephone
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getOrderAddressMobilephone() {
        return orderAddressMobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_address_mobilephone
     *
     * @param orderAddressMobilephone the value for t_order.order_address_mobilephone
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderAddressMobilephone(String orderAddressMobilephone) {
        this.orderAddressMobilephone = orderAddressMobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_address_latitude
     *
     * @return the value of t_order.order_address_latitude
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Double getOrderAddressLatitude() {
        return orderAddressLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_address_latitude
     *
     * @param orderAddressLatitude the value for t_order.order_address_latitude
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderAddressLatitude(Double orderAddressLatitude) {
        this.orderAddressLatitude = orderAddressLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_address_longitude
     *
     * @return the value of t_order.order_address_longitude
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Double getOrderAddressLongitude() {
        return orderAddressLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_address_longitude
     *
     * @param orderAddressLongitude the value for t_order.order_address_longitude
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderAddressLongitude(Double orderAddressLongitude) {
        this.orderAddressLongitude = orderAddressLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_signed_time
     *
     * @return the value of t_order.order_signed_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getOrderSignedTime() {
        return orderSignedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_signed_time
     *
     * @param orderSignedTime the value for t_order.order_signed_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderSignedTime(Date orderSignedTime) {
        this.orderSignedTime = orderSignedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_commented_time
     *
     * @return the value of t_order.order_commented_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getOrderCommentedTime() {
        return orderCommentedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_commented_time
     *
     * @param orderCommentedTime the value for t_order.order_commented_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderCommentedTime(Date orderCommentedTime) {
        this.orderCommentedTime = orderCommentedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_success_time
     *
     * @return the value of t_order.order_success_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getOrderSuccessTime() {
        return orderSuccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_success_time
     *
     * @param orderSuccessTime the value for t_order.order_success_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderSuccessTime(Date orderSuccessTime) {
        this.orderSuccessTime = orderSuccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_cancel_time
     *
     * @return the value of t_order.order_cancel_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getOrderCancelTime() {
        return orderCancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_cancel_time
     *
     * @param orderCancelTime the value for t_order.order_cancel_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderCancelTime(Date orderCancelTime) {
        this.orderCancelTime = orderCancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.store_id
     *
     * @return the value of t_order.store_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.store_id
     *
     * @param storeId the value for t_order.store_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.store_name
     *
     * @return the value of t_order.store_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.store_name
     *
     * @param storeName the value for t_order.store_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.store_province_code
     *
     * @return the value of t_order.store_province_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getStoreProvinceCode() {
        return storeProvinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.store_province_code
     *
     * @param storeProvinceCode the value for t_order.store_province_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setStoreProvinceCode(String storeProvinceCode) {
        this.storeProvinceCode = storeProvinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.store_city_code
     *
     * @return the value of t_order.store_city_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getStoreCityCode() {
        return storeCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.store_city_code
     *
     * @param storeCityCode the value for t_order.store_city_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setStoreCityCode(String storeCityCode) {
        this.storeCityCode = storeCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.store_ad_code
     *
     * @return the value of t_order.store_ad_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getStoreAdCode() {
        return storeAdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.store_ad_code
     *
     * @param storeAdCode the value for t_order.store_ad_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setStoreAdCode(String storeAdCode) {
        this.storeAdCode = storeAdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.store_white
     *
     * @return the value of t_order.store_white
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getStoreWhite() {
        return storeWhite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.store_white
     *
     * @param storeWhite the value for t_order.store_white
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setStoreWhite(String storeWhite) {
        this.storeWhite = storeWhite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.store_create_time
     *
     * @return the value of t_order.store_create_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getStoreCreateTime() {
        return storeCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.store_create_time
     *
     * @param storeCreateTime the value for t_order.store_create_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setStoreCreateTime(Date storeCreateTime) {
        this.storeCreateTime = storeCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.eshop_id
     *
     * @return the value of t_order.eshop_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEshopId() {
        return eshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.eshop_id
     *
     * @param eshopId the value for t_order.eshop_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopId(String eshopId) {
        this.eshopId = eshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.eshop_name
     *
     * @return the value of t_order.eshop_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEshopName() {
        return eshopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.eshop_name
     *
     * @param eshopName the value for t_order.eshop_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopName(String eshopName) {
        this.eshopName = eshopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.eshopseller_id
     *
     * @return the value of t_order.eshopseller_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEshopsellerId() {
        return eshopsellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.eshopseller_id
     *
     * @param eshopsellerId the value for t_order.eshopseller_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopsellerId(String eshopsellerId) {
        this.eshopsellerId = eshopsellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.eshop_self
     *
     * @return the value of t_order.eshop_self
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEshopSelf() {
        return eshopSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.eshop_self
     *
     * @param eshopSelf the value for t_order.eshop_self
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopSelf(String eshopSelf) {
        this.eshopSelf = eshopSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.eshop_white
     *
     * @return the value of t_order.eshop_white
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEshopWhite() {
        return eshopWhite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.eshop_white
     *
     * @param eshopWhite the value for t_order.eshop_white
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopWhite(String eshopWhite) {
        this.eshopWhite = eshopWhite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.eshop_type
     *
     * @return the value of t_order.eshop_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEshopType() {
        return eshopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.eshop_type
     *
     * @param eshopType the value for t_order.eshop_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopType(String eshopType) {
        this.eshopType = eshopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.eshop_kind
     *
     * @return the value of t_order.eshop_kind
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEshopKind() {
        return eshopKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.eshop_kind
     *
     * @param eshopKind the value for t_order.eshop_kind
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopKind(String eshopKind) {
        this.eshopKind = eshopKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.eshop_self_inventory
     *
     * @return the value of t_order.eshop_self_inventory
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEshopSelfInventory() {
        return eshopSelfInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.eshop_self_inventory
     *
     * @param eshopSelfInventory the value for t_order.eshop_self_inventory
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopSelfInventory(String eshopSelfInventory) {
        this.eshopSelfInventory = eshopSelfInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.eshop_send_type
     *
     * @return the value of t_order.eshop_send_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEshopSendType() {
        return eshopSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.eshop_send_type
     *
     * @param eshopSendType the value for t_order.eshop_send_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopSendType(String eshopSendType) {
        this.eshopSendType = eshopSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.eshop_create_time
     *
     * @return the value of t_order.eshop_create_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getEshopCreateTime() {
        return eshopCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.eshop_create_time
     *
     * @param eshopCreateTime the value for t_order.eshop_create_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopCreateTime(Date eshopCreateTime) {
        this.eshopCreateTime = eshopCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_status
     *
     * @return the value of t_order.order_status
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_status
     *
     * @param orderStatus the value for t_order.order_status
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_source
     *
     * @return the value of t_order.order_source
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getOrderSource() {
        return orderSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_source
     *
     * @param orderSource the value for t_order.order_source
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderSource(String orderSource) {
        this.orderSource = orderSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.abnormal_type
     *
     * @return the value of t_order.abnormal_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getAbnormalType() {
        return abnormalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.abnormal_type
     *
     * @param abnormalType the value for t_order.abnormal_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setAbnormalType(String abnormalType) {
        this.abnormalType = abnormalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.abnormal_remark
     *
     * @return the value of t_order.abnormal_remark
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getAbnormalRemark() {
        return abnormalRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.abnormal_remark
     *
     * @param abnormalRemark the value for t_order.abnormal_remark
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setAbnormalRemark(String abnormalRemark) {
        this.abnormalRemark = abnormalRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.delivery_type
     *
     * @return the value of t_order.delivery_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.delivery_type
     *
     * @param deliveryType the value for t_order.delivery_type
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setDeliveryType(String deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.trading_price
     *
     * @return the value of t_order.trading_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public BigDecimal getTradingPrice() {
        return tradingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.trading_price
     *
     * @param tradingPrice the value for t_order.trading_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setTradingPrice(BigDecimal tradingPrice) {
        this.tradingPrice = tradingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.payable_price
     *
     * @return the value of t_order.payable_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public BigDecimal getPayablePrice() {
        return payablePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.payable_price
     *
     * @param payablePrice the value for t_order.payable_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setPayablePrice(BigDecimal payablePrice) {
        this.payablePrice = payablePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.score
     *
     * @return the value of t_order.score
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.score
     *
     * @param score the value for t_order.score
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.is_split
     *
     * @return the value of t_order.is_split
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getIsSplit() {
        return isSplit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.is_split
     *
     * @param isSplit the value for t_order.is_split
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setIsSplit(String isSplit) {
        this.isSplit = isSplit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.employee_id
     *
     * @return the value of t_order.employee_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.employee_id
     *
     * @param employeeId the value for t_order.employee_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.employee_phone
     *
     * @return the value of t_order.employee_phone
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEmployeePhone() {
        return employeePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.employee_phone
     *
     * @param employeePhone the value for t_order.employee_phone
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEmployeePhone(String employeePhone) {
        this.employeePhone = employeePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.employee_name
     *
     * @return the value of t_order.employee_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.employee_name
     *
     * @param employeeName the value for t_order.employee_name
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.appointment_start_time
     *
     * @return the value of t_order.appointment_start_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getAppointmentStartTime() {
        return appointmentStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.appointment_start_time
     *
     * @param appointmentStartTime the value for t_order.appointment_start_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setAppointmentStartTime(Date appointmentStartTime) {
        this.appointmentStartTime = appointmentStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.appointment_end_time
     *
     * @return the value of t_order.appointment_end_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getAppointmentEndTime() {
        return appointmentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.appointment_end_time
     *
     * @param appointmentEndTime the value for t_order.appointment_end_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setAppointmentEndTime(Date appointmentEndTime) {
        this.appointmentEndTime = appointmentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.eshop_combo_pro_id
     *
     * @return the value of t_order.eshop_combo_pro_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getEshopComboProId() {
        return eshopComboProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.eshop_combo_pro_id
     *
     * @param eshopComboProId the value for t_order.eshop_combo_pro_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setEshopComboProId(String eshopComboProId) {
        this.eshopComboProId = eshopComboProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.combo_price
     *
     * @return the value of t_order.combo_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public BigDecimal getComboPrice() {
        return comboPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.combo_price
     *
     * @param comboPrice the value for t_order.combo_price
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setComboPrice(BigDecimal comboPrice) {
        this.comboPrice = comboPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.total_quantity
     *
     * @return the value of t_order.total_quantity
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Integer getTotalQuantity() {
        return totalQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.total_quantity
     *
     * @param totalQuantity the value for t_order.total_quantity
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setTotalQuantity(Integer totalQuantity) {
        this.totalQuantity = totalQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_create_time
     *
     * @return the value of t_order.order_create_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getOrderCreateTime() {
        return orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_create_time
     *
     * @param orderCreateTime the value for t_order.order_create_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setOrderCreateTime(Date orderCreateTime) {
        this.orderCreateTime = orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.flag_joyCard
     *
     * @return the value of t_order.flag_joyCard
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Integer getFlagJoycard() {
        return flagJoycard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.flag_joyCard
     *
     * @param flagJoycard the value for t_order.flag_joyCard
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setFlagJoycard(Integer flagJoycard) {
        this.flagJoycard = flagJoycard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.flag_two
     *
     * @return the value of t_order.flag_two
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Integer getFlagTwo() {
        return flagTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.flag_two
     *
     * @param flagTwo the value for t_order.flag_two
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setFlagTwo(Integer flagTwo) {
        this.flagTwo = flagTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.flag_three
     *
     * @return the value of t_order.flag_three
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Integer getFlagThree() {
        return flagThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.flag_three
     *
     * @param flagThree the value for t_order.flag_three
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setFlagThree(Integer flagThree) {
        this.flagThree = flagThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.flag_four
     *
     * @return the value of t_order.flag_four
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Integer getFlagFour() {
        return flagFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.flag_four
     *
     * @param flagFour the value for t_order.flag_four
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setFlagFour(Integer flagFour) {
        this.flagFour = flagFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.last_modify_time
     *
     * @return the value of t_order.last_modify_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.last_modify_time
     *
     * @param lastModifyTime the value for t_order.last_modify_time
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.groupon_state
     *
     * @return the value of t_order.groupon_state
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getGrouponState() {
        return grouponState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.groupon_state
     *
     * @param grouponState the value for t_order.groupon_state
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setGrouponState(String grouponState) {
        this.grouponState = grouponState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.branch_id
     *
     * @return the value of t_order.branch_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.branch_id
     *
     * @param branchId the value for t_order.branch_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_code
     *
     * @return the value of t_order.customer_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customer_code
     *
     * @param customerCode the value for t_order.customer_code
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.company_id
     *
     * @return the value of t_order.company_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.company_id
     *
     * @param companyId the value for t_order.company_id
     *
     * @mbggenerated Tue Jan 23 16:56:34 CST 2018
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
}